### ISSUE TITLE
Ability to change user from root to nobody

### ISSUE THREAD

**Issue by brandonros** [binci/binci#102] opened 2019-03-14 16:55 UTC
```
USER nobody
EXPOSE 8080 9090
ENTRYPOINT [ "node", "--max-http-header-size", "65536", "/app/dist/index.js" ]
```

Something like this is the Dockerfile equivalent. Is this possible with binci?

**Comment by Fluidbyte** [comment] 2019-03-14 17:51
Currently, no, but it would be fairly simple to add to both primary container and services by adding to the config/binci.yml:
```
user: {username or uid}
```

then we'd just need a handler in [command#get](https://github.com/binci/binci/blob/master/src/command.js#L114) to parse `cfg.user` and add it into the command return as `--user={username or uid}`.

**Comment by Fluidbyte** [comment] 2019-03-17 19:07
This is a duplicate of #95, addressing there.

**Closed by Fluidbyte** 2019-03-17 19:07 UTC
